name: Sync Static Assets to R2

on:
  push:
    branches: [main]
    paths:
      - 'client/public/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y parallel

      - name: Install Wrangler
        run: npm install -g wrangler@3.15.1

      - name: Upload files
        run: |
          cd client/public
          find . -type f | parallel -j 10 wrangler r2 object put \
            "${{ secrets.R2_BUCKET_NAME }}/{}" \
            --file "{}"
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
