name: Sync Static Assets to R2

on:
  push:
    branches: [main]
    paths:
      - 'client/public/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Upload to R2
        run: |
          cd client/public
          
          # 递归上传所有文件并保留目录结构
          find . -type f | while read file; do
            object_path="${{ secrets.R2_BUCKET_NAME }}/$file"
            echo "Uploading: $file → r2://$object_path"
            wrangler r2 object put "$object_path" --file "$file"
          done
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
